name = "mungo"
target = "erlang"
version = "0.20.1"

description = "A MongoDB driver for Gleam (formerly gleam_mongo)"
licences = ["Apache-2.0"]
links = [
  {title = "gleam", href = "https://gleam.run"},
  {title = "bison", href = "https://hexdocs.pm/bison"},
]
repository = {type = "github", user = "massivefermion", repo = "mungo"}

internal_modules = [
  "mungo/tcp",
  "mungo/scram",
  "mungo/cursor",
  "mungo/client",
]

[dependencies]
bison = "~> 0.28"
gleam_bitwise = "~> 1.3"
gleam_crypto = "~> 0.4"
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.11"
